# Change these first
owner: AzharRizkiZ # Your GitHub organization or username, where this repository lives
repo: Zulma-Status # The name of this repository

sites:
  - name: Zulma Landing Page
    url: https://zulma.id
  - name: Zulma English
    url: https://en.zulma.id
  - name: Zulma Indonesia
    url: https://id.zulma.id
  - name: Zulma Japan
    url: https://jp.zulma.id
  - name: Zulma Blog
    url: https://blog.zulma.id
  - name: Al-Jazari Personal Virtual Assistant
    url: https://al-jazari.zulma.id
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true
  
assignees: # Users to assign downtime issues (optional)
  - AzharRizkiZ
  - AzharRizky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zulma.id
  # baseUrl: /your-repo-name
  logoUrl: https://id.zulma.id/assets/images/AZ.png
  name: Zulma Website Status
  introTitle: "**Zulma Website** is Azhar Rizki Zulma personal website."
  introMessage: This is a status page which uses **real-time** data from our [Zulma Status](https://github.com/AzharRizkiZ/Zulma-Status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Creator
      href: https://zulma.id
  favicon: https://id.zulma.id/assets/images/favicon.ico
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
